// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9_rm3ZPZ3bDdQQ3T-f1kz-7x3czrwsnI',
    appId: '1:804753258623:web:611e341a697095ad00274a',
    messagingSenderId: '804753258623',
    projectId: 'sosmedproject-e95b1',
    authDomain: 'sosmedproject-e95b1.firebaseapp.com',
    storageBucket: 'sosmedproject-e95b1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYBFeW38jfbast1hgPK0_DhJlnieNKlRQ',
    appId: '1:804753258623:android:737fc07bba6d48cb00274a',
    messagingSenderId: '804753258623',
    projectId: 'sosmedproject-e95b1',
    storageBucket: 'sosmedproject-e95b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbm2AaUBr4g8T4pijyyxhrsb9TAZrFy_M',
    appId: '1:804753258623:ios:6595bcf7d9995fef00274a',
    messagingSenderId: '804753258623',
    projectId: 'sosmedproject-e95b1',
    storageBucket: 'sosmedproject-e95b1.appspot.com',
    iosBundleId: 'com.example.frontSosmed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbm2AaUBr4g8T4pijyyxhrsb9TAZrFy_M',
    appId: '1:804753258623:ios:6595bcf7d9995fef00274a',
    messagingSenderId: '804753258623',
    projectId: 'sosmedproject-e95b1',
    storageBucket: 'sosmedproject-e95b1.appspot.com',
    iosBundleId: 'com.example.frontSosmed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9_rm3ZPZ3bDdQQ3T-f1kz-7x3czrwsnI',
    appId: '1:804753258623:web:ea6339b139ef06be00274a',
    messagingSenderId: '804753258623',
    projectId: 'sosmedproject-e95b1',
    authDomain: 'sosmedproject-e95b1.firebaseapp.com',
    storageBucket: 'sosmedproject-e95b1.appspot.com',
  );
}
